#pragma once

#define DIVIDER_MIN 0.7f
#define DIVIDER_MAX 4.0f
#define INCREASE_DIVIDER_PEAK 8200
#define DECREASE_DIVIDER_PEAK 4500
#define DECREASE_DIVIDER_SECONDS 10

#define OFF_THRESHOLD 2500
#define OFF_SECONDS 30

#define ESTIMATE_SAMPLES_PER_SECOND 40

#define FLOATING_AVG_MIN_BASE 90000