[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
framework = arduino
board_build.core = earlephilhower
board_build.mcu = rp2350

monitor_port = /dev/ttyACM0
monitor_speed = 115200
extra_scripts =
    pre:load-env.py
lib_deps =
    bodmer/TFT_eSPI@2.5.43
    adafruit/Adafruit NeoPixel@^1.12.0
    https://github.com/pschatzmann/arduino-audio-tools.git

build_flags =
    -D USER_SETUP_LOADED=1
;    -D USE_HSPI_PORT
    -D ILI9341_DRIVER=1

;    -D TFT_MISO=47
    -D TFT_MISO=16
;    -D TFT_MOSI=38
    -D TFT_MOSI=19
;    -D TFT_SCLK=48
    -D TFT_SCLK=18

;    -D TFT_CS=1
    -D TFT_CS=17
;    -D TFT_DC=2
    -D TFT_DC=22
;    -D TFT_RST=4
    -D TFT_RST=20
;    -D TOUCH_CS=3
    -D TOUCH_CS=21

    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D LOAD_FONT6=0
    -D LOAD_FONT7=0
    -D LOAD_FONT8=0
    -D LOAD_GFXFF=1
    -D SMOOTH_FONT=1

    -D SPI_FREQUENCY=70000000
    -D SPI_READ_FREQUENCY=27000000
    -D SPI_TOUCH_FREQUENCY=2500000

;    -D UPLOAD_OTA
;    -D WAIT_FOR_SERIAL
;    -D TEST_LEDS
    -D USE_AUDIO_LOGGING
    -D PICO_LOG_LEVEL=debug
    -D CDEBUG

[env:wired]
upload_protocol = picotool